[ 2023-05-03 13:28:10,796 ] 224 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[ 2023-05-03 13:28:10,796 ] 224 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2023-05-03 13:28:14,559 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 13:28:14] "GET / HTTP/1.1" 200 -
[ 2023-05-03 13:28:14,670 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 13:28:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2023-05-03 13:28:17,748 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 13:28:17] "GET /predictdata HTTP/1.1" 200 -
[ 2023-05-03 13:28:33,136 ] 1741 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anujvaghani0/anaconda3/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/anujvaghani0/Desktop/project/ML End To End Projects using CI:CD pipeline/app.py", line 39, in predict_datapoint
    results=predict_pipeline.predict(pred_df)
TypeError: PredictPipeline.predict() takes 1 positional argument but 2 were given
[ 2023-05-03 13:28:33,138 ] 224 werkzeug - INFO - 127.0.0.1 - - [03/May/2023 13:28:33] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
